### ISSUE TITLE
extraction-summary

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langserve#104]
![image](https://github.com/langchain-ai/langserve/assets/11986836/e9087f07-a982-48a6-9202-0c90cae74be9)

another playground not working as expected: https://github.com/langchain-ai/langchain/blob/langserve-templates/templates/extraction-summary/extraction_summary/chain.py
i can see that chain runs (thanks to tracing) but nothing shows up in UI. is because of function call?

**Comment by dqbd** [comment]
Cannot replicate anymore, closing for now.
