### ISSUE TITLE
chain.stream() hangs on end

### ISSUE THREAD

**Issue by hinthornw** [langchain-ai/langserve#128]
The remote runnable goes through all the chunks then freezes. The server side run is marked as done. Haven't debugged yet.

```
for chunk in chain.stream(
           {"text": text, "chat_history": chat_history, "last_run_id": last_run_id},
       ):
         on_chunk(chunk)
         results.append(chunk)
```

**Comment by eyurtsev** [comment]
What template? is this with call backs?

**Comment by hinthornw** [comment]
Was with https://github.com/langchain-ai/langchain/tree/master/templates/chat-bot-feedback/chat_bot_feedback but haven't reproduced on recent versions
