### ISSUE TITLE
Unable to bootstrap - `langchain` cli missing 

### ISSUE THREAD

**Issue by tigerinus** [langchain-ai/langserve#149]
According to README.md

> To use the langchain CLI make sure that you have a recent version of `langchain` installed
and also `typer`. (`pip install langchain typer` or `pip install "langchain[cli]"`)
> 
> ```sh
> langchain ../path/to/directory
> ```
>
> And follow the instructions...

However after `pip install langchain typer` (also tried `pip install "langchain[cli]"`), `langchain` command is not found...

**Comment by efriis** [comment]
Oops updating the docs here! Try `pip install -U "langchain-cli[serve]"`.
