### ISSUE TITLE
Adding chunk to stream fails on dict

### ISSUE THREAD

**Issue by glennbach** [langchain-ai/langserve#154]
I'm building a rag chain, and have the rag portions on the server side and the chat history on the client side. When I stream, I'm getting dict chunks which breaks in client.py:547. If I change the block from:

```python
if final_output:
  final_output += chunk
else:
  final_output = chunk
```

to 

```python
if final_output:
  if isinstance(final_output, dict):
    final_output.update(chunk)
  else:
    final_output += chunk
else:
  final_output = chunk
```

it works. Am I using this in a way that it wasn't intended, or can a solution like this be included?

Thanks,

Glenn

**Comment by eyurtsev** [comment]
Thanks! Will release a fix tomorrow. Any chance you have a short snippet I could use for a unit-test?

**Comment by glennbach** [comment]
Excellent, thanks! What sort of snippet would you be looking for?GlennOn Nov 1, 2023, at 7:30 PM, Eugene Yurtsev ***@***.***> wrote:﻿
Thanks! Will release a fix tomorrow. Any chance you have a short snippet I could use for a unit-test?

**Comment by eyurtsev** [comment]
Fixed in newest release. If you bump into any more issues, minimal code or chain or url to chain/code would be helpful to see to add more unit testing. Thanks for reporting!
