### ISSUE TITLE
langserve dependency conflict with gradio: pydantic

### ISSUE THREAD

**Issue by tigerinus** [langchain-ai/langserve#156]
```
gradio 4.0.2 requires pydantic>=2.0
langserve 0.0.21 requires pydantic<2,>=1
```

Would be great to let langserve align with gradio dependency. Thanks!

**Comment by eyurtsev** [comment]
Thanks for reporting -- we're not supporting pydantic v2 yet -- see https://github.com/tiangolo/fastapi/issues/10360

**Comment by eyurtsev** [comment]
https://github.com/langchain-ai/langserve/pull/181 -- adds pydantic v2 support, although without openapi spec generation

**Comment by eyurtsev** [comment]
Released -- please read README for pydantic section with guidelines on how to use v1 namespace correctly when working with pydantic 2
