### ISSUE TITLE
upgraded from langserve-0.0.22 to 0.0.24/0.0.25, `/invoke` API is gone

### ISSUE THREAD

**Issue by tigerinus** [langchain-ai/langserve#207]
![image](https://github.com/langchain-ai/langserve/assets/7172560/f3f6ee7b-85ac-433b-b7b4-a62324601d99)

This breaks our app. How do I get the `/invoke` API back?

Thanks.

**Comment by eyurtsev** [comment]
If you're using Pydantic V2, docs won't be populated for some of the endpoints, other parts of the API including playground should work. This was a workaround to get support for pydantic V2. See the readme section that discusses pydantic compatibility. Let me know if this is not consistent with what you're seeing.
