### ISSUE TITLE
Cannot use POST requests

### ISSUE THREAD

**Issue by MohammedShokr** [langchain-ai/langserve#214]
I'm currently in the process of familiarizing myself with Langserve and am actively exploring its functionalities. In my attempt to run the provided examples, I've encountered an issue specifically related to routes utilizing POST requests, such as ```/invoke```, ```/stream```, and ```/batch```. Unfortunately, despite my efforts, I'm unable to interact with these routes successfully. Notably, the only routes accessible to me are of the GET type, as depicted in the attached image for reference. Your guidance on resolving this matter would be greatly appreciated.

P.S. I've experimented with various examples from diverse sources, yet the persistent issue remains consistent across all instances.

![image](https://github.com/langchain-ai/langserve/assets/63115488/04621943-57a7-41f8-8937-5ca7b46a1b73)

**Comment by eyurtsev** [comment]
Hi @MohammedShokr,

Please see the section on pydantic compatibility in the README.

The API endpoints are up, but docs won't be generated for them with pydantic v2.

You can use pydantic 1, or use requests/curl to post or use the RemoteRunnable client to interact with invoke/batch/stream etc.

Hope this helps!
