### ISSUE TITLE
Playground can't load assets when using APIRouter

### ISSUE THREAD

**Issue by anhi** [langchain-ai/langserve#233]
Hi,

in a modularized application with APIRouter-instances that set their own prefix, loading the playground does not work, as the prefix path is not prepended for the assets.

This seems like a simple fix: replacing line 1032 of server.py with

`f"{namespace}/playground" if isinstance(app, FastAPI) else f"{app.prefix}{namespace}/playground",`

works for me. I've prepared a corresponding pull request.

**Comment by eyurtsev** [comment]
Thanks for the PR -- I'm taking a look -- will commandeer to add tests

**Comment by eyurtsev** [comment]
Had to open a new PR to push changes. Closing this PR in favor of: https://github.com/langchain-ai/langserve/pull/236
