### ISSUE TITLE
Playground not working due to incorrect mimetype in index.js

### ISSUE THREAD

**Issue by parkerhancock** [langchain-ai/langserve#245]
I can't get the playground to load when using langserve because the index.js file is served with the mimetype "text/plain" and thus my browser (Chrome/Brave/Firefox) refuse to run it. Here are the response headers as reported by Chrome DevTools:
![image](https://github.com/langchain-ai/langserve/assets/633163/ea3cc91a-edbd-4d54-a8c4-67e070983d5a)

So, there are two problems here:

1. The index.js file is being served with an incorrect mimetype, causing the playground to fail, and 
2. When the playground fails, a blank page is returned.

On 2, the HTML source code for the playground endpoint looks like this:

```html
<body>
 <div id="root"></div>
  <script>
    try {
      window.CONFIG_SCHEMA = . . .
      window.INPUT_SCHEMA = . . . 
    } catch (error) {
      // pass
    }
  </script>
</body>
```
And thus, when the page fails to load, because the try/catch block does nothing, no informative error message is returned.

**Comment by eyurtsev** [comment]
Thanks for reporting @parkerhancock

**Comment by parkerhancock** [comment]
No problem! Also, if it helps, this issue is present on Windows PC's, but not Mac's. The identical example works fine on OSX.

**Comment by eyurtsev** [comment]
Source of issue is: https://bugs.python.org/issue43975

**Comment by eyurtsev** [comment]
Seems that mitigation is: https://docs.python.org/3/library/mimetypes.html#mimetypes.init

**Comment by trannhatquy** [comment]
@eyurtsev how to fix the langserve playground not found error. Thank you
