### ISSUE TITLE
Custom CallbackHandlers when chain is invoked

### ISSUE THREAD

**Issue by jmaness** [langchain-ai/langserve#311]
Currently, I haven't found a way to configure request-based CallbackHandlers described at https://python.langchain.com/docs/modules/callbacks/#where-to-pass-in-callbacks.  It looks like 
It looks like https://github.com/langchain-ai/langserve/blob/main/langserve/api_handler.py#L570 configures an `AsyncEventAggregatorCallback` but no other handlers. Is there a way to configure this behavior. 

Essentially, I'd like to use a tool like langfuse to trace all steps, and I'm aware that Langsmith is likely the preferred tool. However, since Langsmith is private beta and only available via SaaS, Langsmith isn't really an option for my use case. Is there a way to accomplish similar tracing request callbacks?

**Comment by eyurtsev** [comment]
Not yet, I'll expose a way to do that

**Comment by jmaness** [comment]
Thanks @eyurtsev. This change seems to work well. I look forward to the next release.

**Comment by eyurtsev** [comment]
Available as of: https://github.com/langchain-ai/langserve/releases/tag/v0.0.36

**Comment by samithaj** [comment]
@jmaness can you please share a example code how to add langfuse to langserve

**Comment by tzsombor95** [comment]
Did you find a solution to connect langfuse callbackhandler from client side? @jmaness or @samithaj

**Comment by jmaness** [comment]
@samithaj @tzsombor95 Here's an adaption of the solution I actually implemented:

```
def _add_tracing(
        config: Dict[str, Any],
        request: Request
) -> Dict[str, Any]:
    """
    Config modifier function to add a tracing callback

    :param config: config dict
    :param request: HTTP request
    :return: updated config
    """

    if "callbacks" not in config:
        config["callbacks"] = []

    conversation_id = config["conversation_id"]
    user_id = config["user_id"]

    metadata = {
        "conversation_id": conversation_id,
        "user_id": user_id
    }

    trace = langfuse.trace(
        CreateTrace(
            id=conversation_id,
            metadata=metadata,
        )
    )
    trace_handler = trace.getNewHandler()

    config["callbacks"].extend([trace_handler])
    return config


add_routes(app, my_chain,
           path="/my-chain",
           per_req_config_modifier=_add_tracing,
           config_keys=["configurable", "conversation_id", "user_id"])
```
