### ISSUE TITLE
Extra calls to per_request_config_modifier for playground

### ISSUE THREAD

**Issue by jmaness** [langchain-ai/langserve#325]
When loading the playground page for a route/chain, these requests are being processed through the `per_request_config_modifier` which probably should be excluded:

- `GET <route path>/playground/`
- `GET <route path>/playground/assets/index-6a0f524c.js`
- `GET <route path>/playground/assets/index-52e8ab2f.css`
- `GET <route path>/playground/favicon.ico`

Temporarily, I have worked around this issue by implementing a check in the `per_request_config_modifier` by comparing the url to a regex, but there are corner cases that this doesn't cover (e.g. if `playground` is part of the route path).

**Comment by eyurtsev** [comment]
Do you want to exclude the per_request_config_modifier from being called for all calls to the endpoint?

**Comment by jmaness** [comment]
I was expecting to only run the `per_request_config_modifier` for `/invoke/`, `/batch/` and `/stream/`, and `/stream_log/` endpoints. However, the current behavior includes requests related to the playground page load.

**Comment by eyurtsev** [comment]
Got it. I don't want to disable it for the playground by default; instead would it work if i passed information to the modifier with the identity of the endpoint?

**Comment by jmaness** [comment]
@eyurtsev Thanks, having the identity of the endpoint should help. 

I might have not understood the purposes too for the `per_request_config_modifier`. When I saw it invoked even on the playground page load (i.e. before inputs are entered and the "Start" button is clicked), it seemed like all requests to any URL under `/<route path>/` including static assets resulted in executing `per_request_config_modifier`, but I could not think of use cases where the config should be modified for GET requests for JavaScript or CSS resources, favicon, etc. Instead, I expected the `per_request_config_modifier` to only get executed for calls that invoked the chain, but that was probably a faulty assumption on my part.

However, having the identity of the endpoint would certainly help at least to make the request filtering cleaner.

**Comment by eyurtsev** [comment]
Aah of course. I was thinking of this as requests made to the runnable via the playground, but this is for serving the js assets. Should probably disable that by default as well as for other end-points, will take care of it next week.

**Comment by eyurtsev** [comment]
https://github.com/langchain-ai/langserve/pull/342

**Comment by eyurtsev** [comment]
Fix released here: https://github.com/langchain-ai/langserve/releases/tag/v0.0.37
