### ISSUE TITLE
ValueError: [TypeError("'async_generator' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

### ISSUE THREAD

**Issue by tiankuo007** [langchain-ai/langserve#345]
I want to filter response of stream_log, so my code is as following:
```python

class CustomRunnable(RemoteRunnable):
    async def astream_log(self, input, config, **kwargs):
        async for log in super().astream_log(input, config, **kwargs):
            yield log

runnable = RemoteRunnable("http://localhost:8000/agent_chain")
@app.post("/agent_chain/stream_log")
async def custom_stram_log(input: dict):
    async for log in runnable.astream_log(input=input["input"], config=input["config"]):
        yield log

add_routes(
    app,
    agent,
    path="/agent_chain",
)
```
Why is output of astream_log not iterable since its result is AsyncIterator[RunLogPatch]? 
And I can not debug the above code ,is it for "RemoteRunnable" that I have to attach another process related to "runnable"?

**Comment by eyurtsev** [comment]
Hi @tiankuo007,

astream log has a built in filter as part of its API that might be helpful -- if not, would love to know what's missing from the API to accommodate your use case.

Could you provide a full snippet / explanation of what you want the code to do?

The current snippet has a number of issues with it:

1. The code defines CustomRunnable but doesn't use it. 
2. The /agent_chain/stream_log/ endpoint is defined twice (first implementation will win)
3.  `runnable` which is a remote runnable is used by the server itself  -- but the servers should not be talking to itself via http.

**Comment by eyurtsev** [comment]
Going to close this issue for now assuming resolved. @tiankuo007 feel free to re-open if you still have issues.
