### ISSUE TITLE
Add astream_events

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langserve#402]
This PR got merged in langchain_core adding astream_events. We'll want to expose it in langserve to make it easier to get streaming results: https://github.com/langchain-ai/langchain/discussions/16175

**Comment by rever1and** [comment]
Just makes me a little confused.

What's the difference between `stream_log` and `astream_events`? are stream_log a workaround way to have `token by token` features?

**Comment by eyurtsev** [comment]
@rever1and take a look at the example for streaming stuff with an agent to get token by token streaming: https://python.langchain.com/docs/modules/agents/how_to/streaming#custom-streaming-with-events

astream_events = astream_log  + parsing and schema normalization

It should be easier to use than the astream_log API

But either of them supports token by token streaming.

There are a few gotchyas with token by token streaming depending on which version of langchain you're on (e.g., you may need to set `streaming=True` on the underlying LLM). Take a look at the notebook above for an example that streams token by token.

**Comment by eyurtsev** [comment]
Deprecating in favor of: https://github.com/langchain-ai/langserve/issues/413 (created a duplicate issue by mistake)
