### ISSUE TITLE
RunnableWithMessageHistory does not work for RemoteRunnable

### ISSUE THREAD

**Issue by rever1and** [langchain-ai/langserve#407]
Hi, I tried to use RunnableWithMessageHistory around RemoteRunnalble, but it failed to work

```
    runnable = RemoteRunnable("http://xxxxxxx/chat/")                                    
    return RunnableWithMessageHistory(                                                            
        runnable,                                                                                 
        RedisChatMessageHistory,                                                     
        input_messages_key="question",                                                            
        history_messages_key="chat_history",                                                      
    ).with_config({"run_name": "app"}) 
```

failed with

```
TypeError: Object of type RedisChatMessageHistory is not JSON serializable  
```

I checked the source code and find the configurable is not serializable.

https://github.com/langchain-ai/langserve/blob/a7c2a94bb78bd1ac193a031143b95fb6bae0eae3/langserve/client.py#L278

which is inserted into configurable by RunnableWithMessageHistory

https://github.com/langchain-ai/langchain/blob/9e95699277fe0db3bfee1654276a43bfba9ecc64/libs/core/langchain_core/runnables/history.py#L320

**Comment by eyurtsev** [comment]
HI @rever1and, Would you be able to include a minimal reproducible example?

**Comment by eyurtsev** [comment]
Actually I might know what this is, will update once resolved

**Comment by rever1and** [comment]
> HI @rever1and, Would you be able to include a minimal reproducible example? (i.e., with all required imports etc) It'll make it easier for me to debug / and see how to resolve the issue.

ok, but looks like you've already reproduce that...do you still need that now?

**Comment by eyurtsev** [comment]
Thanks I'm all set will release fix in a few days

**Comment by eyurtsev** [comment]
Closing issue as fix was merged and released.
