### ISSUE TITLE
Cannot add custom templates with langchain add langchain app add --project-dir

### ISSUE THREAD

**Issue by shellsniper** [langchain-ai/langserve#408]
I created a langchain app template by using:
```
langchain template new hello-world
```

However, when I executed `langchain app add --pip --project-dir ./templates/hello-world`, it returned as following:

```
No packages installed. Exiting.
```

as the docs instructed:

**langchain cli**
- add                    Adds the specified template to the current LangServe app.
- --project-dir                PATH  The project directory [default: None]

Please kindly let me know how to resolve this issue, thanks in advance.

Best,
Levon

**Comment by alexnodeland** [comment]
I'm getting the same issue here @shellsniper 

Any feedback on this from the Langchain team?

**Comment by eyurtsev** [comment]
cc @efriis

**Comment by eyurtsev** [comment]
Could you include versions of langchain, langchain-cli and langchain core? @alexnodeland  / @shellsniper

**Comment by alexnodeland** [comment]
Surely, here are all `Langchain` related packages' versions

```
langchain==0.1.3
langchain-cli==0.0.21
langchain-community==0.0.16
langchain-core==0.1.16
langserve==0.0.39
langsmith==0.0.83
```

**Comment by efriis** [comment]
Hey there! You should create a new app with `langchain app new hello-world`. The `template` namespace is for people developing new templates, not adding existing ones :)

Let me know if you have any more issues!

**Comment by efriis** [comment]
Ah great case! Will add to my todo list to support those file paths better.

In the meantime, feel free to keep using your current flow. If I'm not planning on publishing templates, I often also just create files in `app/` that I import into `server.py`. You can see how I did it in the Exa demo here: https://www.youtube.com/watch?v=dA1cHGACXCo
