### ISSUE TITLE
didn't get response for dynamic RunnableParallel in playground

### ISSUE THREAD

**Issue by shaojun** [langchain-ai/langserve#411]
Hi, my api needs to support input one content, and a list of prompts, then each prompt combined with the content concurently send to model for chatting, it's like multiple reviewers are reviewing a same article to give different suggestions.

this is the code:

```python
import uvicorn
from fastapi import FastAPI
from langchain.prompts import ChatPromptTemplate
# from langchain_community.chat_models import ChatOpenAI
from langserve import add_routes
from fastapi import FastAPI, File, UploadFile
import pathlib
from model_builder import ChatModelBuilder, ChatModelBuilderModelTypeEnum
from langchain.schema.runnable import RunnableLambda
from langchain_core.runnables import RunnableParallel
import json
import datetime
from langchain.prompts import ChatPromptTemplate
import os
from langserve import add_routes
from model_builder import ChatModelBuilder, ChatModelBuilderModelTypeEnum
from langserve import CustomUserType
from langchain_core.runnables import RunnableParallel, Runnable
from typing import Any, Dict, List, Tuple, Mapping
from langchain_openai import ChatOpenAI
app = FastAPI(
    title="LangChain Server",
    version="1.0",
    description="A simple api server using Langchain's Runnable interfaces",
)

class MultiExpertsSummarizeRequest(CustomUserType):
    content: str
    expert_prompts: list[str]


class MultiExpertsSummarizeService:

    @staticmethod
    def process(request: MultiExpertsSummarizeRequest):
        prompts: list[ChatPromptTemplate] = []
        for expert_prompt in request.expert_prompts:
            prompts.append(ChatPromptTemplate.from_messages([
                ("system", expert_prompt),
                ("human", request.content)
            ]))
        model = ChatOpenAI()
        maps: Mapping[str, Runnable] = {}
        for index, expert_prompt in enumerate(prompts):
            expert_chain = expert_prompt | model
            maps.update({str(index): expert_chain})
        return maps


add_routes(
    app,
    RunnableLambda(MultiExpertsSummarizeService.process).with_types(
        input_type=MultiExpertsSummarizeRequest) | RunnableParallel(),
    path="/services/MultiExpertsSummarize",
)

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=9000)
```
when i was playing at http://localhost:9000/services/MultiExpertsSummarize/playground/
there's empty Output.
could you help?

**Comment by eyurtsev** [comment]
@shaojun any chance you can produce a minimal server side script to investigate. Anything to even shave 10 mins of work will help :)

**Comment by shaojun** [comment]
> @shaojun any chance you can produce a minimal server side script to investigate. Anything to even shave 10 mins of work will help :)

i've updated the post.

**Comment by rever1and** [comment]
> | RunnableParallel(),

I just think that you use LECL incorrectly, you can write expert chain in dict so it will automaticly convert into RunnableParallel. The last RunnableParallel is confused here. However, I'm a newbie, just for you to reference

**Comment by shaojun** [comment]
> > | RunnableParallel(),
> 
> I just think that you use LECL incorrectly, you can write expert chain in dict so it will automaticly convert into RunnableParallel. The last RunnableParallel is confused here. However, I'm a newbie, just for you to reference

the `RunnableParallel()` will get the previous step's output as its input, which is the `maps: Mapping[str, Runnable]`.

**Comment by shaojun** [comment]
@eyurtsev could you help to take a look?

**Comment by ahmabboud** [comment]
@shaojun Did you find the solution? I have also encountered the same issue.
