### ISSUE TITLE
Add endpoint descriptions to add_routes

### ISSUE THREAD

**Issue by annabelleg** [langchain-ai/langserve#430]
With normal FastAPI routes, the function docstrings automatically become the function's description in the Swagger docs, or you can pass in a summary/description/name/etc. 

It would be useful to either enable this with `add_routes` automatically or pass in a `description` as a parameter.

The description could be appended to the auto-generated description for each `invoke`/`batch`/... endpoint (e.g., `Given a query, search the internet for a response. Invoke the runnable with the given input and config.`)

**Comment by eyurtsev** [comment]
I think that this is already the case if using pydantic 1? which version of pydantic are you on?

**Comment by eyurtsev** [comment]
Closing issue due to lack of follow up
