### ISSUE TITLE
FastAPI Root Path Option is Ignored

### ISSUE THREAD

**Issue by sbachstein** [langchain-ai/langserve#487]
When deploying behind a reverse proxy, you often rewrite/truncate the HTTP paths and remove some API URL prefix. In order to compensate for that, FastAPI offers the `root_path` option. That way, things like the `/docs` endpoint for the Swagger UI still work.

Langserve, however, does not take the `root_path` into account and, thus, the Langserve Playground does not work correctly. That's because any additional requests (CSS/JS) point to the wrong URL (missing the root path prefix).

**Comment by sbachstein** [comment]
Awesome, thank you for working on it!

**Comment by eyurtsev** [comment]
Merged and will be released in a few

**Comment by eyurtsev** [comment]
Thank you @nat-n
