### ISSUE TITLE
Issue with Serializable ConfigurableField in Langchain when Logging Model to MLflow

### ISSUE THREAD

**Issue by reslleygabriel** [langchain-ai/langserve#528]
I'm working on dynamically configuring the search_kwargs of a retriever at runtime within a Langchain application. My approach involves creating a function that initializes a vectorstore and returns it as a retriever with configurable_fields for runtime configuration.

Here's the function I've developed:

```
def create_retriever():
    return vectorstore.as_retriever(search_kwargs={"k": 10}).configurable_fields(
        search_kwargs=ConfigurableField(
            id="search_kwargs_vectorstore",
            name="Search Kwargs",
            description="The search kwargs to use",
        )
    )
```

To modify the search_kwargs at runtime, I'm using a router chain and an agent chain as follows:

In the router chain I define a configuration dictionary:

`config = {"configurable": {"search_kwargs_vectorstore": {"k": 10}}}`

Then, apply this configuration to the agent chain:

`agent_chain.with_config(config=config)`

However, I encounter an issue when logging the model to MLflow with mlflow.langchain.log_model. The error message is:

`ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:langchain_core.runnables.base.RunnableLambda'`

This error does not occur when I return the retriever without using configurable_fields:

`return vectorstore.as_retriever(search_kwargs={"k": 10})`

Questions:

1. Is the ConstructorError related to MLflow's inability to serialize the ConfigurableField within the retriever?
2. How can I modify the ConfigurableField class or the serialization process to avoid this error and successfully log the model with configurable fields in MLflow?

For reference, here's the documentation on ConfigurableField: [Langchain ConfigurableField Documentation](https://api.python.langchain.com/en/latest/runnables/langchain_core.runnables.utils.ConfigurableField.html#langchain_core.runnables.utils.ConfigurableField)

Any insights or suggestions on how to resolve this issue would be greatly appreciated.

**Comment by eyurtsev** [comment]
Hi @reslleygabriel, this is not a LangServe or LangChain issue. Could you open an issue with mlflow?

**Comment by eyurtsev** [comment]
In case relevant, LangChain offers https://smith.langchain.com/. It has a free tier for developers, so you can test it out to see if it'll suit your application needs.
