### ISSUE TITLE
Documentation error in https://github.com/langchain-ai/langserve/blob/main/langserve/server.py

### ISSUE THREAD

**Issue by clarkebishop** [langchain-ai/langserve#537]
The documentation in line 323 is wrong

```enabled_endpoints=("invoke", "batch", "config_hashes"),```

Should be:

```enabled_endpoints=["invoke", "batch", "config_hashes"],```

It's expecting a list.

**Comment by clarkebishop** [comment]
I did see an exception. My code just enabled the invoke endpoint.
`enabled_endpoints=("invoke")`

The error said something like 'i', 'n', 'v', 'o', 'k', 'e' are not valid endpoints. It spelled out the string "invoke" one character at a time.

**Comment by eyurtsev** [comment]
If you're using a tuple with a single item, you need a trailing slash otherwise it's not a tuple. 

```python
enabled_endpoints=("invoke", )
```

Closing as this is not an issue, but how python syntax works

**Comment by clarkebishop** [comment]
Good point Eugene. Thanks for the clarification.
