### ISSUE TITLE
Langserve stream API returns entire answer, instead of actually token by token

### ISSUE THREAD

**Issue by ca01h** [langchain-ai/langserve#590]
Hello, I built a simple langchain app using custom LLM and langserve. It works well for its invoke API. But not stream API, it returns entire answer after a while, instead of actually streaming the output.

This is my code to implement _stream function in my CustomLLM:
```python
class CustomLLM(LLM):
    def _call(
            self,
            prompt: str,
            stop: Optional[List[str]] = None,
            run_manager: Optional[CallbackManagerForLLMRun] = None,
            **kwargs: Any,
    ) -> str:
        ......
        return text

    def _stream(
            self,
            prompt: str,
            stop: Optional[List[str]] = None,
            run_manager: Optional[CallbackManagerForLLMRun] = None,
            **kwargs: Any
    ) -> Iterator[GenerationChunk]:
        request = self._default_params
        request["question"] = prompt
        request["stream"] = True
        request.update(kwargs)

        res = self._post(request, streaming=True)

        for chunk in res.iter_lines():
            chunk = chunk.decode("utf-8").strip("\r\n")
            parts = chunk.split("data: ", 1)
            chunk = parts[1] if len(parts) > 1 else None
            if chunk is None:
                continue
            if chunk == "[DONE]":
                break

            response = json.loads(chunk)
            chunk = GenerationChunk(text=response["data"]["content"])
            if run_manager:
                run_manager.on_llm_new_token(chunk.text, chunk=chunk)

            yield chunk
```

and langserve part:
```python
llm = CustomLLM()
chain = llm | StrOutputParser()

app = FastAPI(
        title="app",
        version="0.1",
        description="",
    )
add_routes(app, chain)

uvicorn.run(app, host="0.0.0.0", port=8000)
```
And I write some test code to confirm streaming works:
```python
input = "xxxxx"
for chunk in chain.stream(input=input):
      print(chunk, end="", flush=True)
```
It prints the answer token by token.

AND I found this issue #218 ,but it not works for me.

Please help, Thanks !!!

**Comment by eyurtsev** [comment]
What's your langchain core version?

LangServe uses async streaming rather than sync streaming and the LLM you're sharing only implements sync streaming. Newer version of LangChain core will fallback to the sync version of streaming.

To test whether astream streaming works try this:

```python
input = "xxxxx"
async for chunk in chain.astream(input=input):
      print(chunk, end="", flush=True)
```

**Comment by akshaylingamaneni** [comment]
have a weird issue,  have a remote runnable cain, written in lcel, trying to stream in a nextjs app. When running with npm run dev it works. When running with npm run start the fetch fails with internal server error and the entire response is generated at once instead of streaming. I dont understand why it works in run dev and not in run start.
`
 const chain = new RemoteRunnable({ url ,options:{
      headers: {
        'Content-Type': 'text/event-stream',
        Connection: 'keep-alive',
        'Cache-Control': 'no-cache, no-transform',
      },
    }});
        
const stream = await chain.stream({
      human_input: lastMessageContent,
    }, { 'configurable': { 'chat_id': id, 'user_id': user_id } });
    // for await (const chunk of stream) {
    //   console.log(chunk);
    // }
    console.log("response", res)
    return new StreamingTextResponse(stream.pipeThrough(createChatMessageChunkEncoderStream()),{
       headers: {
      'Content-Type': 'text/event-stream',
      Connection: 'keep-alive',
      'Cache-Control': 'no-cache, no-transform',
    },
    });`
    
    Appreciate any help on the same. Kinda stuck.

**Comment by ca01h** [comment]
> What's your langchain core version?
> 
> LangServe uses async streaming rather than sync streaming and the LLM you're sharing only implements sync streaming. Newer version of LangChain core will fallback to the sync version of streaming.
> 
> To test whether astream streaming works try this:
> 
> ```python
> input = "xxxxx"
> async for chunk in chain.astream(input=input):
>       print(chunk, end="", flush=True)
> ```

Yes, Implement async streaming and It prints the answer token by token. Thanks!
