### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by yairyairyair** [langchain-ai/langserve#623]
I saw langserve and it seems super useful,
langchain is already widely used and serving a langchain runnable seems useful.

However langserve license does not allow for a platform (PaaS) that hosts langchain runnables via langserve,
if the license will change to allow these kind of platforms it might be a better developer experience (just host your langchain runnable).
Also it will cause langchain to gain even more users that currently.

Would be happy to discuss if needed, just hope it will allow PaaS hosting in the future (so users wont need to containerize it all)

Thanks!

**Comment by eyurtsev** [comment]
Thanks for the feedback. The license was chosen as such on purpose. At the moment, we're not looking to change it.
