### ISSUE TITLE
is it possible to include the path for stream_log?

### ISSUE THREAD

**Issue by chip-davis** [langchain-ai/langserve#643]
Hi! I was wondering if it is possible to include or exclude the path with stream_log. I know it consumes Runnable so the change would happen there but is there any workaround? I am trying to build a multi-step loader on my frontend. 
For example:
```
event: data

data: {"ops":[{"op":"add","path":"/logs/LangGraph/final_output" ...
```

I would love to be able to say include the path /logs/LangGraph/final_output. This is useful for me as some of the logs don't really have a name, tag, or type that I can reliably use to differentiate

**Comment by eyurtsev** [comment]
Are you able to use astream_events interface instead?

**Comment by chip-davis** [comment]
Ah, yes that works. Thanks!
