### ISSUE TITLE
localhost:8000 always report 404

### ISSUE THREAD

**Issue by gyliu513** [langchain-ai/langserve#65]
I was trying to run the server at https://github.com/langchain-ai/langserve/blob/main/examples/conversational_retrieval_chain/server.py via `python server.py`, it can start up successfully.

But when I open localhost:8000, the browser will report as follows:

<img width="459" alt="Screenshot 2023-10-19 at 11 42 12 AM" src="https://github.com/langchain-ai/langserve/assets/4461983/951a05e5-b39d-4c59-9566-5d4c6c130a9d">

The console report the following:

```console
% python server.py
INFO:     Started server process [55125]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     ::1:52140 - "GET / HTTP/1.1" 404 Not Found
INFO:     ::1:52142 - "GET / HTTP/1.1" 404 Not Found
```

Am I doing anything wrong? Thanks

**Comment by eyurtsev** [comment]
localhost:8000 doesn't have any endpoints on it probably. try `curl localhost:8000/docs`

**Comment by eyurtsev** [comment]
@gyliu513 let me know if that works. We don't want to populate the root path by default since users will almost certaintly have some default behavior for the root path in their existing fast api server

**Comment by gyliu513** [comment]
it still report error even with curl

```console
% curl http://localhost:8000
{"detail":"Not Found"}%
```

**Comment by eyurtsev** [comment]
That's the correct response for http://localhost:8000 it should provide not found since nothing is defined at `/`

Instead:  `curl localhost:8000/docs` i.e., add `docs` as the path

**Comment by gyliu513** [comment]
Good, it works, I think we need to update README a bit to reflect this? Use `curl localhost:8000/docs` but not `curl localhost:8000`

**Comment by eyurtsev** [comment]
https://github.com/langchain-ai/langserve/pull/81
