### ISSUE TITLE
Cannot use the play ground "No applicable renderer found"

### ISSUE THREAD

**Issue by MohammedShokr** [langchain-ai/langserve#653]
I am deploying a Langchain agent using Langserve and I can call the API from python without any problems but when I open the playground I find the inputs field disabled with an error message "No applicable renderer found."
please note that the input to my agent is a dictionary with two keys; `input` and `chat_history`

Here's an image with the error for your reference 
![image](https://github.com/langchain-ai/langserve/assets/63115488/6389ed00-9cdc-4e5e-9056-5c8c2f326f55)

**Comment by Bongomannn** [comment]
I think you should paste also your code here.
