### ISSUE TITLE
"invoke" endpoint doe s not return "context"

### ISSUE THREAD

**Issue by Aillian** [langchain-ai/langserve#661]
i see this bug all around langserve issues...
like here: #461 #301 #618 

Basically the "invoke" endpoint does not return all the outputs returned by the chain, it only returns:
```
{
  "output": {
    "question": "what is blah blah?",
    "answer": "blah blah is ..."
  },
  "callback_events": []
}
```

while when i do `chain.invoke("what is blah blah?")`, it returns:
```
{'context': [Document(page_content='blah blah', metadata={'ID': 123})],
 'question': 'what is blah blah?',
 'answer': 'blah blah is ...'}
```

why are the context and source documents not returned?

**Comment by eyurtsev** [comment]
Specify the output type explicitly so that `context` is documented as an expected output

https://github.com/langchain-ai/langserve/issues/618#issuecomment-2078146837

**Comment by Aillian** [comment]
@eyurtsev thanks this fixed my issue, but why should i specify the types explicitly, it should be "what i see as output should get reflected in the api output"
