### ISSUE TITLE
LangServe Cmd('git') failed due to: exit code(128) 

### ISSUE THREAD

**Issue by lucapqg** [langchain-ai/langserve#689]
I'm not getting create a new LangChain project and install this as the only package. Does anyone have a solution for this?

> │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                               errstr = b"Cloning into                                        │ │
│ │                                        '/home/luca/.config/langchain/git_repos/langchain_ai… │ │
│ │                             p_stderr = <_io.TextIOWrapper name=6 encoding='UTF-8'>           │ │
│ │ read_all_from_possibly_closed_stream = <function                                             │ │
│ │                                        Git.AutoInterrupt.wait.<locals>.read_all_from_possib… │ │
│ │                                        at 0x7fad00b3de10>                                    │ │
│ │                                 self = <git.cmd.Git.AutoInterrupt object at 0x7fad00b735c0>  │ │
│ │                               status = 128                                                   │ │
│ │                               stderr = "Cloning into                                         │ │
│ │                                        '/home/luca/.config/langchain/git_repos/langchain_ai… │ │
│ │                             stderr_b = b"Cloning into                                        │ │
│ │                                        '/home/luca/.config/langchain/git_repos/langchain_ai… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --branch=master --depth=1 -- https://github.com/langchain-ai/langchain.git 
/home/luca/.config/langchain/git_repos/langchain_ai_langchain_git_4fe265c3
  stderr: 'Cloning into '/home/luca/.config/langchain/git_repos/langchain_ai_langchain_git_4fe265c3'...
POST git-upload-pack (364 bytes)
POST git-upload-pack (194 bytes)
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 1248 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by eyurtsev** [comment]
Try again? looks like some transient network issue?

**Comment by eyurtsev** [comment]
I'll close this for now since it looks like a transient
