### ISSUE TITLE
Pass authentication token to RemoteRunnable

### ISSUE THREAD

**Issue by krlng** [langchain-ai/langserve#709]
I'm building an multi-agent setup, where each agent is running in an own service hosted by LangServe. I connect those agents in a service called "workflow" using RemoteRunnable and LangGraph and want to host that service using LangServe as well. This works nicely, how ever all services have to be secured using an Authentication Middleware.

The basic authentication for a service works as well, how ever I don't know how to pass the authentication token I receive in the user-facing workflow service and pass it to the agent services. Is this setup already supported or if not, what would be the best way to make it work?

**Comment by eyurtsev** [comment]
Hi @krlng, there are some auth examples here: https://github.com/langchain-ai/langserve/tree/main/examples/auth

You can also review the options for instantiating a Remote Runnable https://github.com/langchain-ai/langserve/blob/1487bf1ce5cd6ce963bdec6170de85494ef55327/langserve/client.py#L276

**Comment by eyurtsev** [comment]
Closing since this looks like a usage question rather than an issue.
