### ISSUE TITLE
Support for stream_events v2

### ISSUE THREAD

**Issue by matined** [langchain-ai/langserve#724]
Hello,

I cannot find out a way to use stream_events endpoint in its version v2 from langchain 0.2.x.
Is that feature not implemented or it's just a gap in the documentation?

https://python.langchain.com/v0.2/docs/versions/v0_2/migrating_astream_events/

Thanks in advance!

**Comment by eyurtsev** [comment]
Hasn't been implemented here. Do you care if it's configurable server side or controllable by the client?

**Comment by matined** [comment]
I do not need the client's side parameter. The v1's gonna be removed in 0.4, so I think it makes sense to implement just the server side.

I'd be glad if I could help with or follow the implementation, but do not want to start it cuz I'm not into repo and not sure if it's just passing one parameter around or sth more complex😃

**Comment by eyurtsev** [comment]
hmm I'll check if we can revise our deprecation schedule for v1 as well -- we revised a bunch of deprecation timelines from 0.3/0.4 versions all the way to 1 to avoid forcing users to upgrade existing working code.

**Comment by eyurtsev** [comment]
This will be available in 0.3 release -- later today or monday. It must be set on the server side and will be ignored when passed client side.
