### ISSUE TITLE
Questions about LangServe hosting license

### ISSUE THREAD

**Issue by SokichiFujita** [langchain-ai/langserve#730]
Where can LangServe be hosted legally? The license for LangServe (https://github.com/langchain-ai/langserve/blob/main/LICENSE) states that you can't offer it as a hosted service to third parties, but it doesn't specify where you're allowed to host it for your own use. The relevant part of the license says:

> You may not provide the software to third parties as a hosted or managed service, where the service provides users with access to any substantial set of the features or functionality of the software.

This restriction leaves some questions about acceptable hosting locations for personal or internal company use. It would be helpful if the license provided more clarity on this issue.

**Comment by eyurtsev** [comment]
This restriction leaves some questions about acceptable hosting locations for personal or internal company use. 

How so? There is no restriction about hosting locations. The restriction is how on whether you're trying to provide a managed service using fast api to other users as a 3rd party.

If you're doing this internally to developers in the same company to handle on-prem deployments that's fine. 

You're in violation of the license if you're offering a managed service / hosting solution to developers that work in another company.
