### ISSUE TITLE
How to use langgserve with django apis?

### ISSUE THREAD

**Issue by Vaishnavi21721** [langchain-ai/langserve#739]

**Comment by eyurtsev** [comment]
LangServe is for FastAPI. If you're using django, flask or any other web framework, you can create the endpoints yourself. 

1. create endpoint
2. define serialization and deserialization logic

It should be very straight forward as long as you're not trying to create a generic solution across all runnables etc.

The main issue of django (at least last time time that I worked with it) -- is it was more clunky with async and async is useful with LLM calls as they can be slower.

**Comment by Vaishnavi21721** [comment]
Thanks for you valuable response.
