### ISSUE TITLE
Handle long running LangGraphs in Langserve (500 seconds -1000 seconds)

### ISSUE THREAD

**Issue by saurabhlalsaxena** [langchain-ai/langserve#781]
I have a long running langGraph that takes 500-1000 seconds to run and although the api returns 200, the response is not received by the client. Is there a way to configure a webhook or any other solution?

**Comment by eyurtsev** [comment]
You should look at langgraph platform: https://langchain-ai.github.io/langgraph/concepts/langgraph_platform/

It'll handle long running calls and many more features that you'll need!
