### ISSUE TITLE
from httpx._types import AuthTypes, CertTypes, CookieTypes, HeaderTypes, VerifyTypes ImportError: cannot import name 'VerifyTypes' from 'httpx._types' (/usr/local/lib/python3.11/site-packages/httpx/_types.py)

### ISSUE THREAD

**Issue by maryam123errami** [langchain-ai/langserve#799]
I get an error when I try to build a Docker image. Can someone please help me?
from langserve import add_routes
File "/usr/local/lib/python3.11/site-packages/langserve/init.py", line 8, in
from langserve.client import RemoteRunnable
File "/usr/local/lib/python3.11/site-packages/langserve/client.py", line 24, in
from httpx._types import AuthTypes, CertTypes, CookieTypes, HeaderTypes, VerifyTypes
ImportError: cannot import name 'VerifyTypes' from 'httpx._types' (/usr/local/lib/python3.11/site-packages/httpx/_types.py)

langchain-community
psycopg2-binary
tenacity
scikit-learn
pydantic
fastapi
langchain_google_genai
httpx==0.27.2
langgraph
langserve
uvicorn
langchain
langchain-cli
langchain-core
langchain-openai==0.2.10

**Comment by xxsl** [comment]
Solution here: https://github.com/langchain-ai/langserve/issues/796#issuecomment-2511226034

PR: [PR798](https://github.com/langchain-ai/langserve/pull/798)

**Comment by eyurtsev** [comment]
should be resolved in 0.3.1
