### ISSUE TITLE
path param not supported

### ISSUE THREAD

**Issue by harris** [langchain-ai/langserve#85]
version: 0.0.15

## How to reproduce: 
- follow the instructions in https://github.com/langchain-ai/langserve/blob/main/examples/chain/server.py 
- modify the add_routes line to be:
```
add_routes(app, chain, input_type=ChainInput, config_keys=["configurable"], path="/example")
```
- navigate to http://localhost:8000/example/playground. 

## Observation: 
- No applicable renderer found  
![image](https://github.com/langchain-ai/langserve/assets/4535/5770227a-82b4-4ed3-ba3f-cb9139b69a18)

## Expected: 
- inputs rendered properly

**Comment by eyurtsev** [comment]
cc @dqbd

**Comment by harris** [comment]
> The issue is that the widget isn't rendering yet right? (Not that there's an issue with the path param)

Yeah that's the only issue.  The api actually works fine if you use the swagger doc directly.

**Comment by eyurtsev** [comment]
@harris we resolved a playground issue in the newest release -- I suspect will fix what you're seeing as well

**Comment by eyurtsev** [comment]
Resolving for now as I think this was addressed. We had additional enhancements and bug fixes coming up for playground UI.
