### ISSUE TITLE
Set model parameters from request context, eg. Azure AD token

### ISSUE THREAD

**Issue by jwicks** [langchain-ai/langserve#94]
From the examples, I can see how to instantiate a model, eg. ChatOpenAI, using static parameters (eg. `temperature`, `openai_api_X`, etc). I can even see how to make them [configurable w/ static alternatives](https://github.com/langchain-ai/langserve/blob/20875e036266bd5789fa7dee3070ff52513d4a85/examples/chain/server.py#L15).

However, I have a use-case where I need to dynamically set model parameters by introspecting the incoming request. For example -- to set `openai_api_key` to the user's token from incoming Authorization header token when using `openai_api_type="azure_ad"`.

How can I accomplish this with LangServe's Runnable/add_routes pattern? Is there somehow a way to expose the request to [Runnable.bind()](https://python.langchain.com/docs/expression_language/how_to/binding) ?

```python
app = FastAPI(
    title="LangChain Server",
)

model = ChatOpenAI(
    temperature=0.5,
    openai_api_key=token, # This needs to be the user's incoming Authorization header
    openai_api_type="azure_ad",
)

prompt = ChatPromptTemplate.from_template("tell me a joke about {topic}")

add_routes(
    app,
    prompt | model,
    path="/chain",
)
```

**Comment by eyurtsev** [comment]
@jwicks sorry for the delay -- you can't do this just yet, likely a few more days -- it's high priority

Solution likely combines configurable runnables together with a user provided callable that updates the config based on current config + raw request (so should make it possible to add user info / jwt etc.)

**Comment by eyurtsev** [comment]
@jwicks see per request modifier argument in add_routes -- I hope that'll work for your use case

**Comment by jwicks** [comment]
This is exactly what I need. Thanks! Closing issue
